# Generated by Django 4.2.6 on 2023-10-07 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DataValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True)),
                ('string_value', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QWater_backend.data')),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QWater_backend.datatype')),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QWater_backend.location'),
        ),
        migrations.AddField(
            model_name='data',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QWater_backend.status'),
        ),
    ]
