# Generated by Django 4.2.6 on 2023-10-07 11:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('QWater_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='test_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
